# Generated by Django 2.1.1 on 2018-11-09 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('carbs', models.IntegerField()),
                ('sugars', models.IntegerField()),
                ('fibre', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('gi', models.IntegerField()),
                ('healthscore', models.IntegerField()),
                ('type', models.CharField(max_length=45)),
                ('unit', models.CharField(max_length=45)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
