# Generated by Django 2.1.1 on 2018-11-09 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0002_remove_food_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
