# Generated by Django 2.1.1 on 2018-11-09 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
