# Generated by Django 2.1.1 on 2018-11-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20181109_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='user',
            new_name='lovers',
        ),
    ]
