# Generated by Django 2.1.1 on 2018-11-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20181118_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='lovers',
            new_name='loved_by',
        ),
    ]
