# Generated by Django 2.1.1 on 2018-11-18 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0006_auto_20181118_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ignored_by',
            field=models.ManyToManyField(blank=True, related_name='ignored_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='loved_by',
            field=models.ManyToManyField(blank=True, related_name='loved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
