# Generated by Django 2.1.1 on 2018-11-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20181118_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='energy',
            new_name='calories',
        ),
    ]
