# Generated by Django 2.1.1 on 2019-02-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_auto_20190123_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('M', 'Main'), ('S', 'Side'), ('V', 'Vegetables'), ('O', 'Other')], max_length=45),
        ),
    ]
