# Generated by Django 2.1.1 on 2018-11-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20181123_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_has_food',
            name='portion_size',
            field=models.IntegerField(),
        ),
    ]
