# Generated by Django 2.1.1 on 2018-11-24 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20181124_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
