"""
Django settings for FRESHLIFE project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=(99_wh_peolo1p6#z%s+k61jx#i1#c0nky$o3uoupn4q$!@zf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # WAIT!
# Did you remove "v=..." from all your html files?


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'mainApp',
    'calc',
    'planner',
    'myPlans',
    'food',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FRESHLIFE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 'builtins': [
            #     'django.contrib.staticfiles.templatetags.staticfiles',
            # ],
        },
    },
]

WSGI_APPLICATION = 'FRESHLIFE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),
# ]

LOGIN_REDIRECT_URL = '/'

# CSRF_HEADER_NAME = ""

'''
List of Ideas and To-DOs:
    
    0) titles  hnfge
    
    1) Food App
        a. improved search
            - Style search bar
            - Categorised search
            - imporved search filter
        c. rework nutritional values
        j. Make the entire webpage responsive 
        m. remove null=True from Food and exception handling
    
    2) Calculator
        a. Redesign
            - responsive
            - Remake bodyfat chart
        b. Different units (pounds, stones, etc)
        c. 
    
    3) Meal Planner
        a. Make sure algorithms are reworked for new Food model
    
    4) Grid on Main page
    
    5) Whole application:
        a. Move all unnessesary transitions & hovers to pc mediaquery
        b. ??? loading animations ???
        
        
    
    
'''